import type { Service } from "@/types";
import { localize } from "@/lib/i18n/config";

/*
 * Service content is sourced from `AI-Izdehar Website.docx`.
 * No invented facts, figures or clients. All images are null (rendered as
 * branded placeholders) and are replaceable from the CMS / media library.
 */

export const seedServices: Service[] = [
  /* ── Sea Freight ─────────────────────────────────────────── */
  {
    id: "svc-sea-freight",
    slug: "sea-freight",
    name: localize("Sea Freight", "الشحن البحري"),
    short_description: localize(
      "Reliable Global Shipping by Sea",
      "شحن عالمي موثوق عبر البحر",
    ),
    hero_image: null,
    thumbnail: null,
    gallery: [],
    icon: "ship",
    cta: {
      label: localize("Request a Sea Freight Quote", "اطلب عرض سعر للشحن البحري"),
      url: "/quote?service=Sea Freight",
      variant: "primary",
    },
    content: localize(
      [
        "At Al-Izdehar Logistics, we provide reliable, flexible, and cost-effective sea freight solutions designed to connect your business with markets around the world. Whether you are shipping a single container, managing regular commercial shipments, or transporting oversized and specialized cargo, our experienced team works closely with you to ensure your goods move safely, efficiently, and according to your requirements.",
        "With our extensive understanding of international shipping procedures and customs requirements, we manage the logistics process from the point of origin to the final destination, giving our clients greater visibility, control, and peace of mind throughout the entire journey.",
        "## Comprehensive Sea Freight Solutions",
        "Our sea freight services are designed to accommodate different types of cargo, shipment sizes, destinations, and delivery requirements. We provide flexible solutions for both Full Container Load (FCL) and Less than Container Load (LCL) shipments.",
        "## Full Container Load (FCL)",
        "For clients who require an entire container, our FCL solutions provide a secure and efficient way to transport cargo internationally. We coordinate the shipment process from container booking and cargo collection through ocean transportation and final delivery.",
        "## Less than Container Load (LCL)",
        "When your shipment does not require a full container, our LCL service provides a practical and cost-effective alternative. Your cargo can be consolidated with other shipments while maintaining professional handling and coordination throughout the transportation process.",
        "## Global Reach, Local Expertise",
        "International sea freight involves multiple stages, regulations, documents, and parties. At Al-Izdehar Logistics, our team coordinates these elements to help make the shipping process as smooth and efficient as possible. We work with a network of shipping and logistics partners to provide suitable routing options based on destination, cargo type, transit requirements, and cost considerations.",
        "## Safe and Efficient Cargo Transportation",
        "We understand that every shipment represents an important part of your business. That is why we place strong emphasis on reliability, safety, communication, and efficiency throughout the shipping process.",
        "## Port-to-Port or Door-to-Door",
        "Whether you require a traditional port-to-port shipment or a complete door-to-door logistics solution, Al-Izdehar Logistics can coordinate the transportation according to your specific requirements. Our integrated approach allows us to connect sea freight with other transportation modes, including land and air freight, when required, creating a seamless logistics solution from origin to final destination.",
      ].join("\n\n"),
      [
        "في شركة الإزدهار للوجستيات، نقدم حلول شحن بحري موثوقة ومرنة وفعالة من حيث التكلفة، مصممة لربط أعمالك بالأسواق حول العالم. سواء كنت تشحن حاوية واحدة، أو تدير شحنات تجارية منتظمة، أو تنقل بضائع كبيرة الحجم ومتخصصة، يعمل فريقنا ذو الخبرة عن قرب معك لضمان انتقال بضائعك بأمان وكفاءة ووفقاً لمتطلباتك.",
        "بفضل فهمنا العميق لإجراءات الشحن الدولي ومتطلبات الجمارك، ندير العملية اللوجستية من نقطة الانطلاق إلى الوجهة النهائية، مما يمنح عملاءنا رؤية وتحكماً وراحة بال أكبر طوال الرحلة.",
        "## حلول شحن بحري شاملة",
        "صُممت خدمات الشحن البحري لدينا لتناسب مختلف أنواع البضائع وأحجام الشحنات والوجهات ومتطلبات التسليم. نوفر حلولاً مرنة لكل من شحنات الحاوية الكاملة (FCL) والشحنات الأقل من حمولة الحاوية (LCL).",
        "## الحاوية الكاملة (FCL)",
        "للعملاء الذين يحتاجون إلى حاوية كاملة، توفر حلول FCL لدينا طريقة آمنة وفعالة لنقل البضائع دولياً. ننسق عملية الشحن من حجز الحاوية وجمع البضائع مروراً بالنقل البحري وحتى التسليم النهائي.",
        "## الشحنة الأقل من حاوية (LCL)",
        "عندما لا تتطلب شحنتك حاوية كاملة، توفر خدمة LCL لدينا بديلاً عملياً وفعالاً من حيث التكلفة. يمكن دمج بضائعك مع شحنات أخرى مع الحفاظ على المعالجة والتنسيق الاحترافي طوال عملية النقل.",
        "## وصول عالمي وخبرة محلية",
        "يشمل الشحن البحري الدولي مراحل وأنظمة ومستندات وأطرافاً متعددة. في الإزدهار للوجستيات، ينسق فريقنا هذه العناصر لجعل عملية الشحن سلسة وفعالة قدر الإمكان. نعمل مع شبكة من شركاء الشحن واللوجستيات لتوفير خيارات توجيه مناسبة بناءً على الوجهة ونوع البضاعة ومتطلبات العبور واعتبارات التكلفة.",
        "## نقل بضائع آمن وفعال",
        "ندرك أن كل شحنة تمثل جزءاً مهماً من أعمالك. لذلك نولي اهتماماً كبيراً للموثوقية والسلامة والتواصل والكفاءة طوال عملية الشحن.",
        "## من الميناء إلى الميناء أو من الباب إلى الباب",
        "سواء كنت تحتاج إلى شحنة تقليدية من الميناء إلى الميناء أو حلاً لوجستياً متكاملاً من الباب إلى الباب، يمكن للإزدهار للوجستيات تنسيق النقل وفقاً لمتطلباتك الخاصة. يتيح نهجنا المتكامل ربط الشحن البحري بوسائل نقل أخرى، بما في ذلك الشحن البري والجوي عند الحاجة، مما يخلق حلاً لوجستياً متكاملاً من نقطة الانطلاق إلى الوجهة النهائية.",
      ].join("\n\n"),
    ),
    what_we_offer: [
      localize("FCL and LCL shipments", "شحنات الحاوية الكاملة (FCL) والجزئية (LCL)"),
      localize("Import and export shipments", "شحنات الاستيراد والتصدير"),
      localize("Container booking and coordination", "حجز الحاويات والتنسيق"),
      localize("Cargo collection and delivery", "جمع البضائع وتسليمها"),
      localize("Port-to-port and door-to-door solutions", "حلول من الميناء إلى الميناء ومن الباب إلى الباب"),
      localize("Transshipment and international routing", "إعادة الشحن والتوجيه الدولي"),
      localize("Documentation and shipment coordination", "المستندات وتنسيق الشحنات"),
      localize("Customs clearance support", "دعم التخليص الجمركي"),
      localize("Cargo tracking and shipment updates", "تتبع البضائع وتحديثات الشحن"),
      localize("Specialized and oversized cargo solutions", "حلول البضائع المتخصصة وكبيرة الحجم"),
      localize("Coordination with ports, carriers, agents, and other logistics partners", "التنسيق مع الموانئ والناقلين والوكلاء وشركاء اللوجستيات"),
    ],
    features: [
      localize("Experience You Can Trust", "خبرة يمكنك الوثوق بها"),
      localize("Flexible Solutions", "حلول مرنة"),
      localize("Cost Efficiency", "كفاءة في التكلفة"),
      localize("Professional Coordination", "تنسيق احترافي"),
      localize("End-to-End Support", "دعم شامل من البداية إلى النهاية"),
      localize("Client-Focused Service", "خدمة تركز على العميل"),
    ],
    how_it_works: [
      localize("Booking", "الحجز"),
      localize("Cargo Collection", "جمع البضائع"),
      localize("Ocean Transportation", "النقل البحري"),
      localize("Customs & Delivery", "الجمارك والتسليم"),
    ],
    faq: [
      {
        id: "sea-faq-1",
        question: localize("What is FCL?", "ما هو الشحن بالحاوية الكاملة (FCL)؟"),
        answer: localize(
          "FCL (Full Container Load) means your cargo occupies an entire container. It is ideal when you have enough volume to fill a container and want a secure, efficient and dedicated shipping option from booking through final delivery.",
          "تعني FCL (الحاوية الكاملة) أن بضائعك تشغل حاوية كاملة. وهي مثالية عندما يكون لديك حجم كافٍ لملء حاوية وترغب في خيار شحن آمن وفعال ومخصص من الحجز وحتى التسليم النهائي.",
        ),
        sort_order: 1,
      },
      {
        id: "sea-faq-2",
        question: localize("What is LCL?", "ما هو الشحن الأقل من حاوية (LCL)؟"),
        answer: localize(
          "LCL (Less than Container Load) allows your cargo to share container space with other shipments. It is a practical, cost-effective option when your shipment does not require a full container.",
          "يتيح الشحن الأقل من حاوية (LCL) مشاركة مساحة الحاوية مع شحنات أخرى. وهو خيار عملي وفعال من حيث التكلفة عندما لا تتطلب شحنتك حاوية كاملة.",
        ),
        sort_order: 2,
      },
      {
        id: "sea-faq-3",
        question: localize("Can you provide door-to-door sea freight?", "هل يمكنكم توفير شحن بحري من الباب إلى الباب؟"),
        answer: localize(
          "Yes. Our integrated approach connects sea freight with land and customs coordination where required, creating a complete door-to-door logistics solution from origin to final destination.",
          "نعم. يتيح نهجنا المتكامل ربط الشحن البحري بالتنسيق البري والجمركي عند الحاجة، مما يوفر حلاً لوجستياً متكاملاً من الباب إلى الباب من نقطة الانطلاق إلى الوجهة النهائية.",
        ),
        sort_order: 3,
      },
      {
        id: "sea-faq-4",
        question: localize("What documents are required for sea freight?", "ما المستندات المطلوبة للشحن البحري؟"),
        answer: localize(
          "Documentation typically includes commercial invoices, packing lists, bills of lading and any other documents required by the relevant authorities. Our team helps coordinate the required paperwork for your shipment.",
          "تتضمن المستندات عادةً الفواتير التجارية وقوائم التعبئة وبوالص الشحن وأي مستندات أخرى تطلبها الجهات المعنية. يساعد فريقنا في تنسيق الأوراق المطلوبة لشحنتك.",
        ),
        sort_order: 4,
      },
    ],
    related_services: ["customs-clearance", "integrated-logistics", "land-freight"],
    sort_order: 1,
    status: "published",
    seo: {
      seo_title: localize(
        "Sea Freight Services | FCL & LCL Ocean Shipping",
        "خدمات الشحن البحري | شحن FCL و LCL عبر المحيط",
      ),
      seo_description: localize(
        "Reliable, flexible and cost-effective sea freight solutions with FCL and LCL options, door-to-door shipping and customs clearance support.",
        "حلول شحن بحري موثوقة ومرنة وفعالة من حيث التكلفة مع خيارات FCL و LCL وشحن من الباب إلى الباب ودعم التخليص الجمركي.",
      ),
      focus_keyword: localize("Sea Freight", "الشحن البحري"),
      canonical_url: null,
      noindex: false,
      og_title: null,
      og_description: null,
      og_image: null,
      schema_type: "Service",
    },
  },

  /* ── Land Freight ────────────────────────────────────────── */
  {
    id: "svc-land-freight",
    slug: "land-freight",
    name: localize("Land Freight", "الشحن البري"),
    short_description: localize(
      "Reliable Road Transportation Across Borders",
      "نقل بري موثوق عبر الحدود",
    ),
    hero_image: null,
    thumbnail: null,
    gallery: [],
    icon: "truck",
    cta: {
      label: localize("Request a Land Freight Quote", "اطلب عرض سعر للشحن البري"),
      url: "/quote?service=Land Freight",
      variant: "primary",
    },
    content: localize(
      [
        "At Al-Izdehar Logistics, we provide reliable, flexible, and cost-effective land freight solutions designed to connect businesses across local, regional, and international markets. Whether you require a full truckload, partial load, cross-border transportation, or door-to-door delivery, our experienced team works to ensure your cargo reaches its destination safely, efficiently, and on schedule.",
        "With our extensive experience in logistics and customs clearance, we understand the importance of smooth coordination when moving cargo by road. From shipment planning and documentation to customs procedures and final delivery, we provide professional support throughout the transportation process.",
        "## Comprehensive Land Freight Solutions",
        "Our land freight services are designed to accommodate different types of cargo, shipment volumes, destinations, and delivery requirements. We develop transportation solutions based on your cargo characteristics, required delivery time, route, and budget.",
        "## Full Truckload (FTL)",
        "For shipments that require an entire truck, our Full Truckload (FTL) solutions provide a direct and efficient transportation option. FTL services are ideal for larger shipments or cargo that requires dedicated transportation, helping minimize handling and unnecessary stops along the route.",
        "## Less Than Truckload (LTL)",
        "For smaller shipments that do not require a full truck, our Less Than Truckload (LTL) solutions provide a flexible and cost-effective alternative. Your cargo can be transported alongside other compatible shipments, allowing you to optimize transportation costs while maintaining professional handling throughout the journey.",
        "## Cross-Border Land Freight",
        "International road transportation requires careful coordination of routes, documentation, border procedures, and customs requirements. At Al-Izdehar Logistics, we support our clients throughout the cross-border transportation process, helping ensure that shipments move smoothly between countries.",
        "## Flexible Transportation Solutions",
        "Every shipment has different requirements. The right transportation solution depends on factors such as cargo type, shipment size, destination, delivery schedule, and budget. Our team works closely with each client to understand these requirements and identify the most suitable transportation option.",
        "## Door-to-Door Delivery",
        "One of the key advantages of land freight is its ability to provide direct access to the final destination. Road transportation can connect warehouses, factories, distribution centers, businesses, and other locations directly. We can coordinate door-to-door transportation as part of an integrated logistics solution.",
        "## Connecting Ports, Borders, and Businesses",
        "Land freight plays an important role in the global supply chain by connecting ports, airports, warehouses, distribution centers, and final destinations. Our land transportation solutions can be integrated with our sea freight and air freight services, allowing us to create multimodal transportation solutions that support your shipment from its origin through to its final destination.",
      ].join("\n\n"),
      [
        "في شركة الإزدهار للوجستيات، نقدم حلول شحن بري موثوقة ومرنة وفعالة من حيث التكلفة، مصممة لربط الأعمال عبر الأسواق المحلية والإقليمية والدولية. سواء كنت تحتاج إلى حمولة شاحنة كاملة أو حمولة جزئية أو نقل عبر الحدود أو تسليم من الباب إلى الباب، يعمل فريقنا ذو الخبرة لضمان وصول بضائعك إلى وجهتها بأمان وكفاءة وفي الوقت المحدد.",
        "بفضل خبرتنا الواسعة في اللوجستيات والتخليص الجمركي، ندرك أهمية التنسيق السلس عند نقل البضائع براً. من تخطيط الشحنة والمستندات إلى الإجراءات الجمركية والتسليم النهائي، نوفر دعماً احترافياً طوال عملية النقل.",
        "## حلول شحن بري شاملة",
        "صُممت خدمات الشحن البري لدينا لتناسب مختلف أنواع البضائع وأحجام الشحنات والوجهات ومتطلبات التسليم. نطور حلول النقل بناءً على خصائص بضائعك ووقت التسليم المطلوب والمسار والميزانية.",
        "## الحمولة الكاملة (FTL)",
        "للشحنات التي تتطلب شاحنة كاملة، توفر حلول الحمولة الكاملة (FTL) لدينا خيار نقل مباشر وفعال. وتعد خدمات FTL مثالية للشحنات الأكبر أو البضائع التي تتطلب نقلاً مخصصاً، مما يساعد على تقليل المناولة والتوقفات غير الضرورية على طول الطريق.",
        "## الحمولة الجزئية (LTL)",
        "للشحنات الأصغر التي لا تتطلب شاحنة كاملة، توفر حلول الحمولة الجزئية (LTL) لدينا بديلاً مرناً وفعالاً من حيث التكلفة. يمكن نقل بضائعك إلى جانب شحنات متوافقة أخرى، مما يتيح لك تحسين تكاليف النقل مع الحفاظ على المعالجة الاحترافية طوال الرحلة.",
        "## الشحن البري عبر الحدود",
        "يتطلب النقل البري الدولي تنسيقاً دقيقاً للطرق والمستندات وإجراءات الحدود ومتطلبات الجمارك. في الإزدهار للوجستيات، ندعم عملاءنا طوال عملية النقل عبر الحدود، للمساعدة في ضمان انتقال الشحنات بسلاسة بين الدول.",
        "## حلول نقل مرنة",
        "لكل شحنة متطلبات مختلفة. يعتمد حل النقل المناسب على عوامل مثل نوع البضاعة وحجم الشحنة والوجهة وجدول التسليم والميزانية. يعمل فريقنا عن قرب مع كل عميل لفهم هذه المتطلبات وتحديد خيار النقل الأنسب.",
        "## التوصيل من الباب إلى الباب",
        "من أهم مزايا الشحن البري قدرته على الوصول المباشر إلى الوجهة النهائية. يمكن للنقل البري ربط المستودعات والمصانع ومراكز التوزيع والأعمال والمواقع الأخرى مباشرة. يمكننا تنسيق النقل من الباب إلى الباب كجزء من حل لوجستي متكامل.",
        "## ربط الموانئ والحدود والأعمال",
        "يلعب الشحن البري دوراً مهماً في سلسلة التوريد العالمية من خلال ربط الموانئ والمطارات والمستودعات ومراكز التوزيع والوجهات النهائية. يمكن دمج حلول النقل البري لدينا مع خدمات الشحن البحري والجوي، مما يتيح لنا إنشاء حلول نقل متعدد الوسائط تدعم شحنتك من نقطة الانطلاق حتى الوجهة النهائية.",
      ].join("\n\n"),
    ),
    what_we_offer: [
      localize("Full Truckload (FTL) transportation", "نقل بالحمولة الكاملة (FTL)"),
      localize("Less Than Truckload (LTL) transportation", "نقل بالحمولة الجزئية (LTL)"),
      localize("Local and regional transportation", "نقل محلي وإقليمي"),
      localize("Cross-border transportation", "نقل عبر الحدود"),
      localize("Door-to-door delivery", "تسليم من الباب إلى الباب"),
      localize("Port-to-door and door-to-port solutions", "حلول من الميناء إلى الباب ومن الباب إلى الميناء"),
      localize("Cargo collection and final delivery", "جمع البضائع والتسليم النهائي"),
      localize("Customs clearance support", "دعم التخليص الجمركي"),
      localize("Transportation documentation and coordination", "مستندات النقل والتنسيق"),
      localize("Shipment tracking and status updates", "تتبع الشحنات وتحديثات الحالة"),
      localize("Container transportation by road", "نقل الحاويات براً"),
      localize("General commercial cargo transportation", "نقل البضائع التجارية العامة"),
    ],
    features: [
      localize("Experience You Can Trust", "خبرة يمكنك الوثوق بها"),
      localize("Flexible Solutions", "حلول مرنة"),
      localize("Regional & Cross-Border Connectivity", "اتصال إقليمي وعبر الحدود"),
      localize("Customs Clearance Support", "دعم التخليص الجمركي"),
      localize("Cost Efficiency", "كفاءة في التكلفة"),
      localize("End-to-End Coordination", "تنسيق شامل من البداية إلى النهاية"),
      localize("Client-Focused Service", "خدمة تركز على العميل"),
    ],
    how_it_works: [
      localize("Planning", "التخطيط"),
      localize("Cargo Collection", "جمع البضائع"),
      localize("Road Transportation", "النقل البري"),
      localize("Border & Delivery", "الحدود والتسليم"),
    ],
    faq: [
      {
        id: "land-faq-1",
        question: localize("What is the difference between FTL and LTL?", "ما الفرق بين FTL و LTL؟"),
        answer: localize(
          "FTL (Full Truckload) dedicates an entire truck to your shipment, ideal for larger loads. LTL (Less Than Truckload) shares space with other compatible shipments, a cost-effective option for smaller cargo.",
          "تعني FTL (الحمولة الكاملة) تخصيص شاحنة كاملة لشحنتك، وهي مثالية للأحمال الأكبر. أما LTL (الحمولة الجزئية) فتشارك المساحة مع شحنات متوافقة أخرى، وهو خيار فعال من حيث التكلفة للبضائع الأصغر.",
        ),
        sort_order: 1,
      },
      {
        id: "land-faq-2",
        question: localize("Do you handle cross-border transportation?", "هل تتعاملون مع النقل عبر الحدود؟"),
        answer: localize(
          "Yes. We support clients throughout the cross-border transportation process, coordinating routes, documentation, border procedures and customs requirements to help shipments move smoothly between countries.",
          "نعم. ندعم العملاء طوال عملية النقل عبر الحدود، من خلال تنسيق الطرق والمستندات وإجراءات الحدود ومتطلبات الجمارك لضمان انتقال الشحنات بسلاسة بين الدول.",
        ),
        sort_order: 2,
      },
      {
        id: "land-faq-3",
        question: localize("Can land freight be combined with sea or air freight?", "هل يمكن دمج الشحن البري مع الشحن البحري أو الجوي؟"),
        answer: localize(
          "Yes. Our land transportation integrates with sea and air freight to create multimodal solutions, for example moving a container from a seaport inland to its final destination.",
          "نعم. يتكامل النقل البري لدينا مع الشحن البحري والجوي لإنشاء حلول متعددة الوسائط، مثل نقل حاوية من الميناء البحري إلى وجهتها النهائية داخلياً.",
        ),
        sort_order: 3,
      },
    ],
    related_services: ["customs-clearance", "integrated-logistics", "sea-freight"],
    sort_order: 2,
    status: "published",
    seo: {
      seo_title: localize(
        "Land Freight Services | FTL & LTL Road Transportation",
        "خدمات الشحن البري | نقل بري FTL و LTL",
      ),
      seo_description: localize(
        "Reliable land freight and cross-border road transportation with FTL and LTL options, door-to-door delivery and customs clearance support.",
        "شحن بري موثوق ونقل بري عبر الحدود مع خيارات FTL و LTL وتسليم من الباب إلى الباب ودعم التخليص الجمركي.",
      ),
      focus_keyword: localize("Land Freight", "الشحن البري"),
      canonical_url: null,
      noindex: false,
      og_title: null,
      og_description: null,
      og_image: null,
      schema_type: "Service",
    },
  },

  /* ── Customs Clearance ───────────────────────────────────── */
  {
    id: "svc-customs-clearance",
    slug: "customs-clearance",
    name: localize("Customs Clearance", "التخليص الجمركي"),
    short_description: localize(
      "Simplifying Customs. Accelerating Your Business.",
      "تبسيط الجمارك. تسريع أعمالك.",
    ),
    hero_image: null,
    thumbnail: null,
    gallery: [],
    icon: "stamp",
    cta: {
      label: localize("Request a Customs Clearance Quote", "اطلب عرض سعر للتخليص الجمركي"),
      url: "/quote?service=Customs Clearance",
      variant: "primary",
    },
    content: localize(
      [
        "With more than 40 years of experience in customs clearance, Al-Izdehar Logistics provides professional and reliable customs clearance solutions designed to help businesses move their goods efficiently across international borders.",
        "We understand that customs procedures can be complex, time-sensitive, and subject to strict regulations. Our experienced team works closely with clients, customs authorities, shipping lines, ports, and other relevant parties to coordinate the clearance process and help ensure that shipments are processed accurately and efficiently. Our goal is simple: to make customs clearance easier, faster, and more transparent for our clients.",
        "## Our Customs Clearance Expertise",
        "Since our establishment in 1982, customs clearance has been at the heart of the Al-Izdehar business. Over the years, we have developed extensive knowledge of customs procedures, import and export requirements, documentation, and the practical challenges involved in international trade.",
        "## Import & Export Customs Clearance",
        "We provide customs clearance support for both import and export shipments, helping clients navigate the procedures required to move goods across borders. Whether your cargo arrives by sea, land, or air, we can coordinate the customs clearance process as part of your overall logistics solution.",
        "## Accurate Documentation",
        "Proper documentation is one of the most important elements of a successful customs clearance process. Incomplete, inaccurate, or inconsistent documentation can result in delays, additional costs, or complications. Our team carefully reviews and coordinates the information required for customs processing.",
        "## Customs Clearance for Sea, Land & Air Freight",
        "Because customs clearance is closely connected to transportation, our service can be integrated with all major modes of freight. We coordinate customs procedures for containerized and other sea freight shipments, local and cross-border road shipments, and time-sensitive air cargo.",
        "## Professional Coordination",
        "Customs clearance involves more than submitting documents. It requires communication and coordination between multiple parties. Our team works as a central point of coordination between the client and customs authorities, ports, terminals, shipping lines, airlines, transport companies, agents, and other logistics partners.",
        "## Compliance & Attention to Detail",
        "We recognize that customs compliance is essential to international trade. Our team approaches every shipment with attention to detail and a strong commitment to following applicable customs procedures and requirements.",
        "## Reducing Delays and Unnecessary Costs",
        "Customs delays can affect delivery schedules, inventory planning, and overall logistics costs. While customs processing times and decisions are ultimately determined by the relevant authorities, proper preparation and coordination can help reduce avoidable delays.",
      ].join("\n\n"),
      [
        "بفضل خبرة تتجاوز 40 عاماً في التخليص الجمركي، توفر الإزدهار للوجستيات حلول تخليص جمركي احترافية وموثوقة مصممة لمساعدة الأعمال على نقل بضائعها بكفاءة عبر الحدود الدولية.",
        "ندرك أن الإجراءات الجمركية قد تكون معقدة وحساسة للوقت وخاضعة لأنظمة صارمة. يعمل فريقنا ذو الخبرة عن قرب مع العملاء والجهات الجمركية وخطوط الشحن والموانئ والأطراف المعنية الأخرى لتنسيق عملية التخليص وضمان معالجة الشحنات بدقة وكفاءة. هدفنا بسيط: جعل التخليص الجمركي أسهل وأسرع وأكثر شفافية لعملائنا.",
        "## خبرتنا في التخليص الجمركي",
        "منذ تأسيسنا عام 1982، كان التخليص الجمركي في قلب أعمال الإزدهار. على مر السنين، طورنا معرفة واسعة بالإجراءات الجمركية ومتطلبات الاستيراد والتصدير والمستندات والتحديات العملية المتعلقة بالتجارة الدولية.",
        "## التخليص الجمركي للاستيراد والتصدير",
        "نوفر دعم التخليص الجمركي لكل من شحنات الاستيراد والتصدير، لمساعدة العملاء على اجتياز الإجراءات المطلوبة لنقل البضائع عبر الحدود. سواء وصلت بضائعك بحراً أو براً أو جواً، يمكننا تنسيق عملية التخليص الجمركي كجزء من حل اللوجستيات الكامل لديك.",
        "## مستندات دقيقة",
        "تعد المستندات الصحيحة من أهم عناصر نجاح عملية التخليص الجمركي. فالمستندات الناقصة أو غير الدقيقة أو غير المتسقة قد تؤدي إلى تأخيرات وتكاليف إضافية وتعقيدات. يراجع فريقنا بعناية المعلومات المطلوبة للمعالجة الجمركية وينسقها.",
        "## التخليص الجمركي للشحن البحري والبري والجوي",
        "نظراً لارتباط التخليص الجمركي الوثيق بالنقل، يمكن دمج خدمتنا مع جميع وسائل الشحن الرئيسية. ننسق الإجراءات الجمركية لشحنات الحاويات والشحن البحري الأخرى، والشحنات البرية المحلية وعبر الحدود، والبضائع الجوية الحساسة للوقت.",
        "## تنسيق احترافي",
        "التخليص الجمركي يتجاوز مجرد تقديم المستندات. فهو يتطلب التواصل والتنسيق بين أطراف متعددة. يعمل فريقنا كنقطة تنسيق مركزية بين العميل والجهات الجمركية والموانئ والمحطات وخطوط الشحن وشركات الطيران وشركات النقل والوكلاء وشركاء اللوجستيات الآخرين.",
        "## الامتثال والاهتمام بالتفاصيل",
        "ندرك أن الامتثال الجمركي ضروري للتجارة الدولية. يتعامل فريقنا مع كل شحنة باهتمام بالتفاصيل والتزام قوي باتباع الإجراءات والمتطلبات الجمركية المعمول بها.",
        "## تقليل التأخير والتكاليف غير الضرورية",
        "قد تؤثر التأخيرات الجمركية على جداول التسليم وتخطيط المخزون وتكاليف اللوجستيات الإجمالية. ورغم أن أوقات وقرارات المعالجة الجمركية تحددها الجهات المعنية في النهاية، فإن الإعداد والتنسيق المناسبين يمكن أن يساعدا في تقليل التأخيرات التي يمكن تجنبها.",
      ].join("\n\n"),
    ),
    what_we_offer: [
      localize("Import customs clearance", "التخليص الجمركي للاستيراد"),
      localize("Export customs clearance", "التخليص الجمركي للتصدير"),
      localize("Transit and re-export procedures", "إجراءات العبور وإعادة التصدير"),
      localize("Customs documentation preparation and coordination", "إعداد وتنسيق المستندات الجمركية"),
      localize("Customs declarations and submission support", "البيانات الجمركية ودعم التقديم"),
      localize("Classification and tariff-related support", "دعم التصنيف والتعرفة الجمركية"),
      localize("Customs valuation support", "دعم التقييم الجمركي"),
      localize("Coordination with customs authorities", "التنسيق مع الجهات الجمركية"),
      localize("Port and terminal coordination", "التنسيق مع الموانئ والمحطات"),
      localize("Shipping line and carrier coordination", "التنسيق مع خطوط الشحن والناقلين"),
      localize("Inspection and examination coordination", "تنسيق الفحص والمعاينة"),
      localize("Duty and tax calculation support", "دعم احتساب الرسوم والضرائب"),
      localize("Release and delivery coordination", "تنسيق الإفراج والتسليم"),
      localize("Customs-related consultation", "استشارات جمركية"),
    ],
    features: [
      localize("More Than 40 Years of Experience", "خبرة تتجاوز 40 عاماً"),
      localize("Experienced & Professional Team", "فريق خبير ومحترف"),
      localize("Integrated Logistics Support", "دعم لوجستي متكامل"),
      localize("Attention to Detail", "اهتمام بالتفاصيل"),
      localize("Reliable Communication", "تواصل موثوق"),
      localize("Client-Focused Approach", "نهج يركز على العميل"),
    ],
    how_it_works: [
      localize("Document Review", "مراجعة المستندات"),
      localize("Customs Declaration", "البيان الجمركي"),
      localize("Coordination & Inspection", "التنسيق والمعاينة"),
      localize("Release & Delivery", "الإفراج والتسليم"),
    ],
    faq: [
      {
        id: "customs-faq-1",
        question: localize("What is customs clearance?", "ما هو التخليص الجمركي؟"),
        answer: localize(
          "Customs clearance is the process of preparing and submitting the required documentation and coordinating with customs authorities so that goods can legally move across international borders.",
          "التخليص الجمركي هو عملية إعداد وتقديم المستندات المطلوبة والتنسيق مع الجهات الجمركية حتى تتمكن البضائع من الانتقال قانونياً عبر الحدود الدولية.",
        ),
        sort_order: 1,
      },
      {
        id: "customs-faq-2",
        question: localize("What documents are required for customs clearance?", "ما المستندات المطلوبة للتخليص الجمركي؟"),
        answer: localize(
          "Depending on the shipment and applicable regulations, documentation may include commercial invoices, packing lists, bills of lading, air waybills, certificates of origin, import and export permits, product-related certificates and customs declarations.",
          "بحسب الشحنة والأنظمة المعمول بها، قد تتضمن المستندات الفواتير التجارية وقوائم التعبئة وبوالص الشحن وبوالص الشحن الجوي وشهادات المنشأ وتصاريح الاستيراد والتصدير والشهادات المتعلقة بالمنتج والبيانات الجمركية.",
        ),
        sort_order: 2,
      },
      {
        id: "customs-faq-3",
        question: localize("Do you handle import and export clearance?", "هل تتعاملون مع تخليص الاستيراد والتصدير؟"),
        answer: localize(
          "Yes. We provide customs clearance support for both import and export shipments, whether the cargo arrives by sea, land, or air.",
          "نعم. نوفر دعم التخليص الجمركي لشحنات الاستيراد والتصدير على حد سواء، سواء وصلت البضائع بحراً أو براً أو جواً.",
        ),
        sort_order: 3,
      },
      {
        id: "customs-faq-4",
        question: localize("Can customs clearance be combined with freight services?", "هل يمكن دمج التخليص الجمركي مع خدمات الشحن؟"),
        answer: localize(
          "Yes. Our customs clearance integrates with sea freight, land freight and air freight, providing clients with a complete, coordinated logistics solution.",
          "نعم. يتكامل التخليص الجمركي لدينا مع الشحن البحري والبري والجوي، مما يوفر للعملاء حلاً لوجستياً متكاملاً ومنسقاً.",
        ),
        sort_order: 4,
      },
    ],
    related_services: ["sea-freight", "air-freight", "integrated-logistics"],
    sort_order: 3,
    status: "published",
    seo: {
      seo_title: localize(
        "Customs Clearance Services | Import & Export Clearance",
        "خدمات التخليص الجمركي | تخليص الاستيراد والتصدير",
      ),
      seo_description: localize(
        "Professional customs clearance with more than 40 years of experience. Import, export and transit clearance coordinated with authorities, ports and carriers.",
        "تخليص جمركي احترافي بخبرة تتجاوز 40 عاماً. تخليص الاستيراد والتصدير والعبور بالتنسيق مع الجهات والموانئ والناقلين.",
      ),
      focus_keyword: localize("Customs Clearance", "التخليص الجمركي"),
      canonical_url: null,
      noindex: false,
      og_title: null,
      og_description: null,
      og_image: null,
      schema_type: "Service",
    },
  },

  /* ── Air Freight ─────────────────────────────────────────── */
  {
    id: "svc-air-freight",
    slug: "air-freight",
    name: localize("Air Freight", "الشحن الجوي"),
    short_description: localize(
      "Fast, Reliable Shipping Across the Globe",
      "شحن سريع وموثوق حول العالم",
    ),
    hero_image: null,
    thumbnail: null,
    gallery: [],
    icon: "plane",
    cta: {
      label: localize("Request an Air Freight Quote", "اطلب عرض سعر للشحن الجوي"),
      url: "/quote?service=Air Freight",
      variant: "primary",
    },
    content: localize(
      [
        "At Al-Izdehar Logistics, we provide fast, reliable, and flexible air freight solutions designed for businesses that need speed, efficiency, and dependable international transportation.",
        "When delivery time matters, air freight provides one of the fastest ways to move goods between international markets. Whether you are shipping urgent commercial cargo, high-value products, time-sensitive shipments, samples, spare parts, or critical business materials, our experienced team works to coordinate your shipment efficiently from origin to destination.",
        "## Comprehensive Air Freight Solutions",
        "Our air freight services are designed to accommodate different types of cargo, shipment sizes, destinations, and delivery requirements. Whether you require a one-time urgent shipment or regular international air cargo transportation, Al-Izdehar Logistics provides professional coordination and personalized support throughout the shipping process.",
        "## Time-Sensitive Shipping",
        "In today's global marketplace, time can have a direct impact on business operations. Air freight is an ideal solution when speed and reliability are critical. We coordinate with our logistics partners to identify appropriate routing and transportation options based on your shipment's destination, urgency, cargo characteristics, and delivery requirements.",
        "## Global Air Freight Connectivity",
        "Air freight provides businesses with access to markets around the world through an extensive network of international airports and airline connections. We coordinate with airlines, freight agents, airport operators, customs authorities, and other logistics partners to facilitate the movement of your cargo across international borders.",
        "## Door-to-Door Air Freight",
        "Air transportation is only one part of the complete logistics journey. Your cargo still needs to reach the airport, clear customs, and arrive at its final destination. We can coordinate door-to-door air freight solutions, connecting the entire transportation process from the point of collection to final delivery.",
        "## Customs Clearance Support",
        "With more than 40 years of experience in customs clearance, Al-Izdehar has developed extensive knowledge of customs procedures and international trade requirements. Our team can coordinate customs clearance as part of your air freight shipment.",
        "## Professional Cargo Handling",
        "Our team coordinates with the relevant logistics partners to ensure that your shipment receives appropriate attention throughout the transportation process, including time-sensitive, high-value, fragile, and specialized cargo.",
        "## Connecting Air Freight with Other Logistics Services",
        "Air freight can be integrated with our other logistics services to create a complete transportation solution, such as Air Freight + Land Freight + Customs Clearance.",
      ].join("\n\n"),
      [
        "في شركة الإزدهار للوجستيات، نقدم حلول شحن جوي سريعة وموثوقة ومرنة مصممة للأعمال التي تحتاج إلى السرعة والكفاءة والنقل الدولي الموثوق.",
        "عندما يكون وقت التسليم مهماً، يوفر الشحن الجوي أحد أسرع الطرق لنقل البضائع بين الأسواق الدولية. سواء كنت تشحن بضائع تجارية عاجلة أو منتجات عالية القيمة أو شحنات حساسة للوقت أو عينات أو قطع غيار أو مواد أعمال حرجة، يعمل فريقنا ذو الخبرة على تنسيق شحنتك بكفاءة من نقطة الانطلاق إلى الوجهة.",
        "## حلول شحن جوي شاملة",
        "صُممت خدمات الشحن الجوي لدينا لتناسب مختلف أنواع البضائع وأحجام الشحنات والوجهات ومتطلبات التسليم. سواء كنت تحتاج إلى شحنة عاجلة لمرة واحدة أو نقل بضائع جوية دولية منتظمة، توفر الإزدهار للوجستيات تنسيقاً احترافياً ودعماً مخصصاً طوال عملية الشحن.",
        "## شحن حساس للوقت",
        "في السوق العالمية اليوم، يمكن أن يؤثر الوقت بشكل مباشر على العمليات التجارية. يعد الشحن الجوي حلاً مثالياً عندما تكون السرعة والموثوقية أمرين بالغي الأهمية. ننسق مع شركائنا اللوجستيين لتحديد خيارات التوجيه والنقل المناسبة بناءً على وجهة شحنتك ومدى إلحاحها وخصائص البضائع ومتطلبات التسليم.",
        "## اتصال جوي عالمي",
        "يوفر الشحن الجوي للأعمال إمكانية الوصول إلى الأسواق حول العالم من خلال شبكة واسعة من المطارات الدولية وربطات شركات الطيران. ننسق مع شركات الطيران ووكلاء الشحن ومشغلي المطارات والجهات الجمركية وشركاء اللوجستيات الآخرين لتسهيل حركة بضائعك عبر الحدود الدولية.",
        "## شحن جوي من الباب إلى الباب",
        "النقل الجوي ليس سوى جزء واحد من الرحلة اللوجستية الكاملة. فلا تزال بضائعك بحاجة إلى الوصول إلى المطار وتخليصها جمركياً والوصول إلى وجهتها النهائية. يمكننا تنسيق حلول الشحن الجوي من الباب إلى الباب، لربط عملية النقل بالكامل من نقطة الاستلام إلى التسليم النهائي.",
        "## دعم التخليص الجمركي",
        "بفضل خبرة تتجاوز 40 عاماً في التخليص الجمركي، طورت الإزدهار معرفة واسعة بالإجراءات الجمركية ومتطلبات التجارة الدولية. يمكن لفريقنا تنسيق التخليص الجمركي كجزء من شحنة الشحن الجوي لديك.",
        "## معالجة احترافية للبضائع",
        "ينسق فريقنا مع شركاء اللوجستيات المعنيين لضمان حصول شحنتك على الاهتمام المناسب طوال عملية النقل، بما في ذلك البضائع الحساسة للوقت وعالية القيمة والهشة والمتخصصة.",
        "## ربط الشحن الجوي بخدمات اللوجستيات الأخرى",
        "يمكن دمج الشحن الجوي مع خدمات اللوجستيات الأخرى لدينا لإنشاء حل نقل متكامل، مثل الشحن الجوي + الشحن البري + التخليص الجمركي.",
      ].join("\n\n"),
    ),
    what_we_offer: [
      localize("Import and export air freight", "شحن جوي للاستيراد والتصدير"),
      localize("International air cargo transportation", "نقل البضائع الجوية الدولية"),
      localize("Airport-to-airport solutions", "حلول من المطار إلى المطار"),
      localize("Door-to-door air freight", "شحن جوي من الباب إلى الباب"),
      localize("Airport-to-door delivery", "تسليم من المطار إلى الباب"),
      localize("Time-sensitive and urgent shipments", "شحنات حساسة للوقت وعاجلة"),
      localize("Commercial cargo transportation", "نقل البضائع التجارية"),
      localize("High-value and sensitive cargo solutions", "حلول البضائع عالية القيمة والحساسة"),
      localize("Cargo collection and delivery", "جمع البضائع وتسليمها"),
      localize("Airway Bill (AWB) coordination", "تنسيق بوليصة الشحن الجوي (AWB)"),
      localize("Shipment documentation support", "دعم مستندات الشحن"),
      localize("Customs clearance support", "دعم التخليص الجمركي"),
      localize("Cargo tracking and shipment updates", "تتبع البضائع وتحديثات الشحن"),
      localize("Express services", "خدمات سريعة"),
    ],
    features: [
      localize("Speed & Efficiency", "السرعة والكفاءة"),
      localize("More Than 40 Years of Customs Experience", "خبرة جمركية تتجاوز 40 عاماً"),
      localize("Global Connectivity", "اتصال عالمي"),
      localize("Flexible Solutions", "حلول مرنة"),
      localize("End-to-End Coordination", "تنسيق شامل من البداية إلى النهاية"),
      localize("Professional Communication", "تواصل احترافي"),
      localize("Client-Focused Service", "خدمة تركز على العميل"),
    ],
    how_it_works: [
      localize("Cargo Collection", "جمع البضائع"),
      localize("Airport Handling", "المناولة في المطار"),
      localize("Air Transportation", "النقل الجوي"),
      localize("Customs & Final Delivery", "الجمارك والتسليم النهائي"),
    ],
    faq: [
      {
        id: "air-faq-1",
        question: localize("When should I choose air freight?", "متى أختار الشحن الجوي؟"),
        answer: localize(
          "Air freight is ideal when speed and reliability are critical, for urgent commercial cargo, high-value products, time-sensitive shipments, samples, spare parts and other critical business materials.",
          "الشحن الجوي مثالي عندما تكون السرعة والموثوقية أمرين بالغي الأهمية، للبضائع التجارية العاجلة والمنتجات عالية القيمة والشحنات الحساسة للوقت والعينات وقطع الغيار وغيرها من مواد الأعمال الحرجة.",
        ),
        sort_order: 1,
      },
      {
        id: "air-faq-2",
        question: localize("Do you provide door-to-door air freight?", "هل توفرون شحن جوي من الباب إلى الباب؟"),
        answer: localize(
          "Yes. We coordinate door-to-door air freight solutions connecting cargo collection, airport handling, air transportation, customs clearance and final delivery.",
          "نعم. ننسق حلول الشحن الجوي من الباب إلى الباب بربط جمع البضائع والمناولة في المطار والنقل الجوي والتخليص الجمركي والتسليم النهائي.",
        ),
        sort_order: 2,
      },
      {
        id: "air-faq-3",
        question: localize("Can you handle high-value and sensitive cargo?", "هل يمكنكم التعامل مع البضائع عالية القيمة والحساسة؟"),
        answer: localize(
          "Yes. Depending on the nature of the cargo and applicable airline requirements, we can coordinate solutions for time-sensitive, high-value, fragile and specialized cargo.",
          "نعم. بحسب طبيعة البضاعة ومتطلبات شركة الطيران المعمول بها، يمكننا تنسيق حلول للبضائع الحساسة للوقت وعالية القيمة والهشة والمتخصصة.",
        ),
        sort_order: 3,
      },
    ],
    related_services: ["customs-clearance", "integrated-logistics", "land-freight"],
    sort_order: 4,
    status: "published",
    seo: {
      seo_title: localize(
        "Air Freight Services | Fast International Air Cargo",
        "خدمات الشحن الجوي | نقل جوي دولي سريع",
      ),
      seo_description: localize(
        "Fast, reliable air freight solutions for urgent and time-sensitive cargo with door-to-door delivery, AWB coordination and customs clearance support.",
        "حلول شحن جوي سريعة وموثوقة للبضائع العاجلة والحساسة للوقت مع تسليم من الباب إلى الباب وتنسيق AWB ودعم التخليص الجمركي.",
      ),
      focus_keyword: localize("Air Freight", "الشحن الجوي"),
      canonical_url: null,
      noindex: false,
      og_title: null,
      og_description: null,
      og_image: null,
      schema_type: "Service",
    },
  },

  /* ── Integrated Logistics ────────────────────────────────── */
  {
    id: "svc-integrated-logistics",
    slug: "integrated-logistics",
    name: localize("Integrated Logistics Solutions", "الحلول اللوجستية المتكاملة"),
    short_description: localize(
      "One Partner. One Solution. From Origin to Destination.",
      "شريك واحد. حل واحد. من نقطة الانطلاق إلى الوجهة.",
    ),
    hero_image: null,
    thumbnail: null,
    gallery: [],
    icon: "network",
    cta: {
      label: localize("Talk to Our Logistics Team", "تحدث إلى فريقنا اللوجستي"),
      url: "/quote?service=Integrated Logistics",
      variant: "primary",
    },
    content: localize(
      [
        "At Al-Izdehar Logistics, we provide comprehensive Integrated Logistics Solutions designed to simplify the movement of goods from the point of origin to the final destination.",
        "We understand that modern supply chains involve multiple transportation methods, customs procedures, documentation, warehouses, ports, airports, and logistics partners. Managing each stage separately can create unnecessary complexity, delays, and additional costs. Our integrated approach brings these logistics activities together under one coordinated solution, providing businesses with greater convenience, better visibility, efficient coordination, and a single point of contact throughout the logistics journey.",
        "## End-to-End Logistics Management",
        "Our goal is to make logistics simple for our clients. Instead of managing multiple service providers for different parts of the transportation process, clients can rely on Al-Izdehar Logistics to coordinate the key stages of their shipment.",
        "## Multimodal Transportation Solutions",
        "Different shipments require different transportation methods. In many cases, the most efficient logistics solution involves combining multiple modes of transport, including Sea Freight + Land Freight, Air Freight + Land Freight, Sea Freight + Customs Clearance + Land Freight, and Air Freight + Customs Clearance + Final Delivery.",
        "## Customs Clearance Integration",
        "Customs clearance is an essential part of international logistics, and it should not be treated as a separate process. With more than 40 years of experience in customs clearance, Al-Izdehar provides an important advantage when coordinating international shipments.",
        "## Door-to-Door Logistics",
        "Our integrated logistics solutions can provide door-to-door transportation, coordinating the movement of cargo from the supplier or point of origin through to the final destination, including cargo collection, export procedures, freight, customs clearance, inland transportation, warehousing and final delivery.",
        "## Supply Chain Coordination",
        "Effective logistics is more than simply moving cargo. It requires coordination between multiple activities and stakeholders. Our team acts as a central point of coordination, helping ensure that information and shipments move efficiently between the different stages of the logistics process.",
        "## Tailored Logistics Solutions",
        "Every business has different logistics requirements. Our team takes into consideration factors such as type of cargo, shipment size and volume, origin and destination, required delivery time, transportation mode, customs requirements, storage requirements, and budget.",
        "## Warehousing & Distribution",
        "Where required, our integrated logistics solutions can incorporate warehousing and distribution as part of the overall supply chain, helping businesses manage their inventory and cargo flow more efficiently.",
        "## Cost-Efficient Logistics Planning",
        "An integrated logistics approach can help businesses identify opportunities to improve transportation efficiency and control logistics costs. Our objective is to develop a solution that provides the best overall value for your business.",
      ].join("\n\n"),
      [
        "في شركة الإزدهار للوجستيات، نقدم حلول لوجستية متكاملة شاملة مصممة لتبسيط حركة البضائع من نقطة الانطلاق إلى الوجهة النهائية.",
        "ندرك أن سلاسل التوريد الحديثة تتضمن وسائل نقل متعددة وإجراءات جمركية ومستندات ومستودعات وموانئ ومطارات وشركاء لوجستيين. فإدارة كل مرحلة على حدة قد تخلق تعقيداً وتأخيرات وتكاليف إضافية غير ضرورية. يجمع نهجنا المتكامل هذه الأنشطة اللوجستية معاً في حل منسق واحد، مما يوفر للأعمال راحة أكبر ورؤية أفضل وتنسيقاً فعالاً ونقطة اتصال واحدة طوال الرحلة اللوجستية.",
        "## إدارة لوجستية شاملة من البداية إلى النهاية",
        "هدفنا هو جعل اللوجستيات بسيطة لعملائنا. بدلاً من إدارة مزودي خدمات متعددين لأجزاء مختلفة من عملية النقل، يمكن للعملاء الاعتماد على الإزدهار للوجستيات لتنسيق المراحل الرئيسية لشحناتهم.",
        "## حلول نقل متعدد الوسائط",
        "تتطلب الشحنات المختلفة وسائل نقل مختلفة. في كثير من الحالات، يتضمن الحل اللوجستي الأكثر كفاءة الجمع بين وسائل نقل متعددة، بما في ذلك الشحن البحري + الشحن البري، والشحن الجوي + الشحن البري، والشحن البحري + التخليص الجمركي + الشحن البري، والشحن الجوي + التخليص الجمركي + التسليم النهائي.",
        "## دمج التخليص الجمركي",
        "التخليص الجمركي جزء أساسي من اللوجستيات الدولية، ولا ينبغي التعامل معه كعملية منفصلة. بفضل خبرة تتجاوز 40 عاماً في التخليص الجمركي، توفر الإزدهار ميزة مهمة عند تنسيق الشحنات الدولية.",
        "## لوجستيات من الباب إلى الباب",
        "يمكن لحلولنا اللوجستية المتكاملة توفير النقل من الباب إلى الباب، لتنسيق حركة البضائع من المورد أو نقطة الانطلاق حتى الوجهة النهائية، بما في ذلك جمع البضائع وإجراءات التصدير والشحن والتخليص الجمركي والنقل الداخلي والتخزين والتسليم النهائي.",
        "## تنسيق سلسلة التوريد",
        "اللوجستيات الفعالة تتجاوز مجرد نقل البضائع. فهي تتطلب التنسيق بين أنشطة وأطراف متعددة. يعمل فريقنا كنقطة تنسيق مركزية للمساعدة في ضمان انتقال المعلومات والشحنات بكفاءة بين المراحل المختلفة للعملية اللوجستية.",
        "## حلول لوجستية مخصصة",
        "لكل عمل متطلبات لوجستية مختلفة. يراعي فريقنا عوامل مثل نوع البضاعة وحجم الشحنة وكميتها ونقطة الانطلاق والوجهة ووقت التسليم المطلوب ووسيلة النقل ومتطلبات الجمارك ومتطلبات التخزين والميزانية.",
        "## التخزين والتوزيع",
        "عند الحاجة، يمكن لحلولنا اللوجستية المتكاملة تضمين التخزين والتوزيع كجزء من سلسلة التوريد الشاملة، لمساعدة الأعمال على إدارة مخزونها وتدفق بضائعها بكفاءة أكبر.",
        "## تخطيط لوجستي فعال من حيث التكلفة",
        "يمكن للنهج اللوجستي المتكامل أن يساعد الأعمال على تحديد فرص تحسين كفاءة النقل والتحكم في التكاليف اللوجستية. هدفنا هو تطوير حل يوفر أفضل قيمة إجمالية لأعمالك.",
      ].join("\n\n"),
    ),
    what_we_offer: [
      localize("End-to-End Logistics Management", "إدارة لوجستية شاملة من البداية إلى النهاية"),
      localize("Multimodal Transportation (Sea + Land, Air + Land)", "نقل متعدد الوسائط (بحري + بري، جوي + بري)"),
      localize("Customs clearance integration", "دمج التخليص الجمركي"),
      localize("Door-to-door logistics", "لوجستيات من الباب إلى الباب"),
      localize("Supply chain coordination", "تنسيق سلسلة التوريد"),
      localize("Warehousing and distribution", "التخزين والتوزيع"),
      localize("Shipment visibility and communication", "رؤية الشحنات والتواصل"),
      localize("Cost-efficient logistics planning", "تخطيط لوجستي فعال من حيث التكلفة"),
    ],
    features: [
      localize("One Point of Contact", "نقطة اتصال واحدة"),
      localize("More Than 40 Years of Experience", "خبرة تتجاوز 40 عاماً"),
      localize("Complete Transportation Solutions", "حلول نقل متكاملة"),
      localize("Professional Coordination", "تنسيق احترافي"),
      localize("Flexible & Scalable", "مرونة وقابلية للتوسع"),
      localize("Client-Focused Approach", "نهج يركز على العميل"),
    ],
    how_it_works: [
      localize("Supplier / Origin", "المورد / نقطة الانطلاق"),
      localize("Transportation", "النقل"),
      localize("Port / Airport & Customs", "الميناء / المطار والجمارك"),
      localize("Warehousing", "التخزين"),
      localize("Final Delivery", "التسليم النهائي"),
    ],
    faq: [
      {
        id: "int-faq-1",
        question: localize("What is an integrated logistics solution?", "ما هو الحل اللوجستي المتكامل؟"),
        answer: localize(
          "An integrated logistics solution brings together multiple stages of the supply chain — sea, land and air freight, customs clearance, warehousing and final delivery — under one coordinated service with a single point of contact.",
          "الحل اللوجستي المتكامل يجمع مراحل متعددة من سلسلة التوريد — الشحن البحري والبري والجوي والتخليص الجمركي والتخزين والتسليم النهائي — في خدمة منسقة واحدة بنقطة اتصال واحدة.",
        ),
        sort_order: 1,
      },
      {
        id: "int-faq-2",
        question: localize("Can you provide door-to-door logistics?", "هل يمكنكم توفير لوجستيات من الباب إلى الباب؟"),
        answer: localize(
          "Yes. We coordinate door-to-door transportation from the supplier or point of origin through to the final destination, including collection, freight, customs clearance and delivery.",
          "نعم. ننسق النقل من الباب إلى الباب من المورد أو نقطة الانطلاق حتى الوجهة النهائية، بما في ذلك الاستلام والشحن والتخليص الجمركي والتسليم.",
        ),
        sort_order: 2,
      },
      {
        id: "int-faq-3",
        question: localize("Which transport modes can be combined?", "ما وسائل النقل التي يمكن دمجها؟"),
        answer: localize(
          "We combine sea freight, land freight and air freight with customs clearance to create multimodal solutions such as Sea + Land, Air + Land, Sea + Customs + Land, and Air + Customs + Final Delivery.",
          "نجمع الشحن البحري والبري والجوي مع التخليص الجمركي لإنشاء حلول متعددة الوسائط مثل بحري + بري، وجوي + بري، وبحري + جمارك + بري، وجوي + جمارك + تسليم نهائي.",
        ),
        sort_order: 3,
      },
    ],
    related_services: ["sea-freight", "air-freight", "land-freight"],
    sort_order: 5,
    status: "published",
    seo: {
      seo_title: localize(
        "Integrated Logistics Solutions | End-to-End Supply Chain",
        "حلول لوجستية متكاملة | سلسلة توريد شاملة",
      ),
      seo_description: localize(
        "End-to-end integrated logistics combining sea, land and air freight with customs clearance, warehousing and door-to-door delivery. One partner, one solution.",
        "حلول لوجستية متكاملة شاملة تجمع الشحن البحري والبري والجوي مع التخليص الجمركي والتخزين والتسليم من الباب إلى الباب. شريك واحد، حل واحد.",
      ),
      focus_keyword: localize("Integrated Logistics", "اللوجستيات المتكاملة"),
      canonical_url: null,
      noindex: false,
      og_title: null,
      og_description: null,
      og_image: null,
      schema_type: "Service",
    },
  },
];
